# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb3079a3c1f89a8fa5141c659c8c64168a150481dd385290190bc6050f63ffcb1485eb758007d345f79272742c84bf2120b5f9f15e587b22aab1679080e1c5f4

test:
  secret_key_base: 5f395d0d4cdd49045ba5bd12e3dc93a594c23dc1959a67e4fed44b26b55ff454fefc62bf56178b3db263d3664f0039a15434bbcecb24674734190009c6c07290

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
